### ISSUE TITLE
public NuGet release for netcoreapp1.1

### ISSUE THREAD

**Issue by valamelkor** [isukces/EfCore.Shaman#15]
Is it possible to create a public NuGet version for netcoreapp?

I was able to compile it and link directly as assembly to the project and everything worked fine, until I tried dotnet-ef cli. It throws weird exception

```
> dotnet ef migrations add Initial
...
Could not load file or assembly 'EfCore.Shaman, Version=1.0.17155.57, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
I even tried to set absolute hint path in .csproj
```
<ItemGroup>
    <Reference Include="EfCore.Shaman">
      <HintPath>..\packages\EfCore.Shaman\EfCore.Shaman.dll</HintPath>
      <HintPath>C:\Users\Andrei\Documents\Visual Studio 2017\Projects\myapp\packages\EfCore.Shaman\EfCore.Shaman.dll</HintPath>
    </Reference>
</ItemGroup>
```
Actually I managed this to run somehow (did not found out an actual solution yet, but after some cleanups-
rebuilds it start working) but it is a real pain. It should reported to EF core team. 

So, why not publish .net core version to NuGet?

**Comment by isukces** [comment]
I've just commited new version that contains package for both net4.5.1 and netstandard1.6. Compiled nuget packages will be available on public repository soon. Please leave fitback about this version.

**Comment by valamelkor** [comment]
Thanks! Current lib state seems to be compiling and working fine for .net core, however there still issue with cli unable to load assembly. Could you please publish current version to NuGet?

**Comment by isukces** [comment]
New [nuget](https://www.nuget.org/packages/EfCore.Shaman/) is available. Please leave comments after upgrade package in your application.

**Comment by valamelkor** [comment]
Thank you for update. From official nuget package works good in VS and from ps. 

I will send fill a bug for EF team about not able to load linked assemblies

**Comment by isukces** [comment]
Please check current nuget packages. Can we close this issue now?

**Comment by valamelkor** [comment]
Sure. It worked like a miracle. Thanks!
