### ISSUE TITLE
After Deleting table previous migration throws error on execution: Unable to find table ...

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#16]
Say there is Initial migration script which creates most of tables and in it at the end of Up method we have:
````migrationBuilder.FixMigrationUp<CoreTemplateContext>(); // For proper column order````

Then we delete one table, for example we delete table Item, by deleting entity class Item and removing its DbSet.
Then we create new migration DropTableItem.
Now if first script was already executed to database, second script would pass as well.
However when scirpts are run on new database that requires all scripts to be executed, first script in this case throws exception:

> Unable to find table Item.

Reason why this is happening is that FixMigrationUp is looking for all entities so that it can fix their column order.
And since this entity Item no longer exist it throws error (not being aware that the table is deleted in one of following scripts.)
I think that this should be fixed in a way that it does not throw exception but just skips fixing columns for those entities that are not found (it implicitly means that those table are deleted in next scripts so the order does not matter any more).

**Comment by borisdj** [comment]
I have made following fix for this:
In class `ModelFixer.cs`
method `private void FixOnModelCreatingForTable(CreateTableOperation table)`
instead of
````
if (entity == null)
    throw new Exception($"Unable to find table {table.Schema}.{table.Name}.");
````
used
````
if (entity != null)
{
    // rest of the code from that method
    ...
}
````

**Comment by isukces** [comment]
Thank you for information. My approach for solving problem has been commited [here.](https://github.com/isukces/EfCore.Shaman/commit/fd3bf7293a863a220ad284ae45a5ca7aac038d69) Please confirm if it fits your requirements.

**Comment by borisdj** [comment]
You are welcome.
Yes, since logic is the same and it works, I've just tested it.
Thx for fix, it fits.
