### ISSUE TITLE
Error when compiling solution EfCore.Shaman.Core.sln

### ISSUE THREAD

**Issue by albertolo** [isukces/EfCore.Shaman#19]
I'm trying to compilye libraries , but I get this error, is there something I need to do? 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7027	Error signing output with public key from file 'key.snk' -- File not found.	EfCore.Shaman	C:\x\EfCore.Shaman\src\EfCore.Shaman\CSC	1	Active

thanks 
Alberto

**Comment by isukces** [comment]
See explanation [http://efcoreshaman.com/](http://efcoreshaman.com/).

> Assembly distributed with nuget package is signed with key.snk that is not included with github repository. mksnk.bat script file is included instead. It it running automatically during building process.
