### ISSUE TITLE
[UniqueIndex] attribute not working

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#2]
I have tried the library and column sorting works good, but when I added [UniqueIndex] on some columns no index was created.
What could be the reason, am I doing something wrong in the configuration, or could this be some bug?

I am also curious how should it have work, does it created appropriate code in the migration Up method itself for creation of this Index, that is visible, or does it only just change the migration code behind the scene on executing update-database?

**Comment by borisdj** [comment]
I found the solution, it was about configuration.
Instead of
`this.FixOnModelCreating(modelBuilder);`
it should be
`this.FixOnModelCreating(modelBuilder, new ShamanOptions().WithDefaultServices());`

This now works in .NetFramework, library can be from nuget.
However in .NetCore where I have loaded source code and made fixes mentioned on previous issue, generated migration is invalid:
`migrationBuilder.CreateIndex(
	name: "IX_Customer_UniqueKey_UniqueKey",
	table: "Customer",
	columns: new[] { "UniqueKey", "UniqueKey" },
	unique: true);`

It somehow make Index on like 2 same column, and migration can't be run.
I model there is only one column and one Index:
`[UniqueIndex]`
`public Guid UniqueKey { get; set; }`

Corect code should be:
`migrationBuilder.CreateIndex(
	name: "IX_Customer_UniqueKey",
	table: "Customer",
	column: "UniqueKey",
	unique: true);`

I couldn't figure this out yet.

**Comment by isukces** [comment]
You’re right. I’ve found problem related to index last week and solved. GitHub version is fixed. I plan to collect minor changes and release new nugget package this week.

**Comment by borisdj** [comment]
At the moment I have solution that is working, but it's great to have it in the nuget as well, especially for others who will be using it.
Are you planing to add .NetCore version with this release? I could upload project with changes I've made, although you already have them in comments.
And would it be possible to have both version in single nuget with few IFs or they have to separate libraries?

**Comment by isukces** [comment]
Probably it's possible. Personally, I have not tested. Would you please send .NetCore version of Shaman?

**Comment by borisdj** [comment]
I have added download links for Core version in issue 1.

**Comment by borisdj** [comment]
I think this issue can also be closed.

**Comment by isukces** [comment]
Ok. Thank you for your involvement.

**Comment by borisdj** [comment]
You are welcome, and thank you for the library itself.
