### ISSUE TITLE
Support for singular Table names

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#3]
If I want tables to be singular without having to put `[Table(TableName")]` attributes on all classes, I used:
`foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())`
 ` entityType.Relational().TableName = entityType.DisplayName();`

But when using that and this library, migration fails:
_Unable to find table ...._
Do you have any suggestions how to make both work?

EDIT:
I figured out one solution, requires small change in code
Add IF segment at beginning of _GetByTableName_ method

`public DbSetInfo GetByTableName(string tableName)`
`        {`
`            if (!_dbSets.ContainsKey(tableName))`
`            {`
`                string tableNamePlural = tableName + "s";`
`                string tableNamePlural2 = tableName + "es";`
`                if (_dbSets.ContainsKey(tableNamePlural))`
`                    tableName = tableNamePlural;`
`                else if(_dbSets.ContainsKey(tableNamePlural2))`
`                    tableName = tableNamePlural2;`
`            }`
`            DbSetInfo entity;`
`            _dbSets.TryGetValue(tableName, out entity);`
`            return entity;`
`        }`

**Comment by isukces** [comment]
When table name is changed with entityType.Relational().TableName the information about new name is managed by ModelBuilder. Shaman uses ModelInfo to investigate model details. It doesn't have direct access to ModelBuilder. 
Similar problem is with MS identity tables like AspNetUsers (Shaman recognizes this AspNetUsers as Users)

I have to find another way to solve this. I don't want make changes in GetByTableName because responsibility of finding proper table names is not here.

**Comment by borisdj** [comment]
Just to add that I made a little more complex code for setting all tables singular.
Line in the first post
`entityType.Relational().TableName = entityType.DisplayName();`
overrides all tables names to class name even when I put explicit attribute [Table("TableName")] on some tables.
I think it's better that you can configure all tables to be singular but still be able to set custom tables names on some, so I made changes and now that override is done only for Entities without [Table] attribute.
`    public static class ModelBuilderExtensions
    {
        public static void RemovePluralizingTableNameConvention(this ModelBuilder modelBuilder)
        {
            foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
            {
                var namespaceString = (new EntityBase()).GetType().Namespace;
                var entityName = entityType.DisplayName(); // for setting table names by Entity class(singular) and not by DbSet (plural)
                //entityType.ClrType.Name; // alternative way

                Type type = Type.GetType(namespaceString + "." + entityName);
                object entity = Activator.CreateInstance(type);
                var tableAttribute = entity.GetType().GetTypeInfo().GetCustomAttribute<TableAttribute>();

                if (tableAttribute == null) // if table name explicitly set by [Table("TableName")] attribute do nothing, override to default name only when there is no attribute
                    entityType.Relational().TableName = entityName;
            }
        }
    }`

**Comment by isukces** [comment]
Please check if latest changes meets your requirements. Some info can be found in this [post](http://efcoreshaman.com/manual-changes-with-modelbuilder.html). Public nuget repository has not yet been updated so you have to use github sources.

**Comment by borisdj** [comment]
It still does not work it I don't alter GetByTableName method.
I have downloaded new code, implemented IShamanFriendlyDbContext on MyDbContext:
`public DbContextCreationMode CreationMode { get; set; } = DbContextCreationMode.Normal;`
and in OnModelCreating:
`base.OnModelCreating(modelBuilder);`
`var er = modelBuilder.Model.GetEntityTypes().Single(a => a.ClrType == typeof(Customer));`
`er.Relational().TableName = "Customer";`
`modelBuilder.FixOnModelCreating(this);`

DbSet is
`public DbSet<Customer> Customers { get; set; }`
and Entity
`public class Customer { ...`

And the Exception I get: **Unable to find table Customer.**
come from here:
`_dbSets.TryGetValue(tableName, out entity);`
tableName is "Customer" but this dictionary still has "Customer**s**"

**Comment by isukces** [comment]
Should work now. Similar scenario is included in test [T06_ShouldHaveTableNameWithPrefix](https://github.com/isukces/EfCore.Shaman/blob/8fe55cc7ce9c237f1e67ad9a9cd11e61583c83db/src/EfCore.Shaman.Tests/ModelInfoTests.cs#L116). Please check also [new service](http://efcoreshaman.com/removepluralizingtablenameservice.html).

**Comment by borisdj** [comment]
Setting all singular and/or custom tables Name, as well as new service for this purpose, works well for .NetFramework.
However now I can't make it build for .NetCore.
I will add comment with details on first issue:
[netcoreapp1.1 not working](https://github.com/isukces/EfCore.Shaman/issues/1)
since this one is about .NetCore version.

**Comment by isukces** [comment]
Try to use 
```
public static ShamanOptions GetShamanOptions()
{
    return ShamanOptions.Default.With(new RemovePluralizingTableNameService());
}
```
in your DbContext. Look [here](https://github.com/isukces/EfCore.Shaman/blob/master/src/EfCore.Shaman.Tests/Model/SingularTableNamesDbContext.cs) for example.

**Comment by borisdj** [comment]
That did it, thanks.
You could add comment about Singularization in README.

**Comment by borisdj** [comment]
However now _update-database_ throws an Error.
I have:
```
var shamanOptions = ShamanOptions.Default.With(new RemovePluralizingTableNameService());
this.FixOnModelCreating(modelBuilder, shamanOptions);`
```

and the end of Up method:
'migrationBuilder.FixMigrationUp<AppContext>();'

And when running update-'database' I get:
```
Applying migration '20170331080526_Initial'.
System.Exception: Unable to find table User.
```

I have updated project with this scenario on previous link.

**Comment by isukces** [comment]
`FixMigrationUp` also needs `ShamanOptions`. If you don't provide it then engine will try to use `GetShamanOptions` (if available) or just `ShamanOptions.Default`. In my opinion it's better to provide `GetShamanOptions` static method instead of remember to set customized options in each `FixMigrationUp`.

**Comment by borisdj** [comment]
Got it now.
