### ISSUE TITLE
System.Exception: Unable to find table 

### ISSUE THREAD

**Issue by mattmckinstry** [isukces/EfCore.Shaman#4]
Getting the following

System.Exception: Unable to find table Configs.
   at EfCore.Shaman.ModelFixer.FixOnModelCreatingForTable(CreateTableOperation table)
   at EfCore.Shaman.ModelFixer.FixMigrationUp(MigrationBuilder migrationBuilder)
   at Web.Migrations.InitialSchema.Up(MigrationBuilder migrationBuilder) in C:\Matt\Web\Migrations\20170126151126_InitialSchema.cs:line 32
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to find table Configs.

This is my Sample Migration

```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Configs",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    CreatedDate = table.Column<DateTime>(nullable: false, defaultValueSql: "GETDATE()"),
                    DisplayName = table.Column<string>(maxLength: 100, nullable: false),
                    LastUpdatedDate = table.Column<DateTime>(nullable: true),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Value = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Configs", x => x.Id);
                });
            

            migrationBuilder.FixMigrationUp<ARRDbContext>();
        }
```

```
public class Config : Entity
{
	[Required]
	[StringLength(50)]
	public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string DisplayName { get; set; }

        [Required]
	public string Value { get; set; }
}
```

```
[Serializable]
	public abstract class Entity
	{
		public long Id { get; set; }

		public DateTime CreatedDate { get; set; }

		public DateTime? LastUpdatedDate { get; set; }

		public static bool operator ==(Entity a, Entity b)
		{
			if (ReferenceEquals(a, null) && ReferenceEquals(b, null))
			{
				return true;
			}

			if (ReferenceEquals(a, null) || ReferenceEquals(b, null))
			{
				return false;
			}

			return a.Equals(b);
		}

		public static bool operator !=(Entity a, Entity b)
		{
			return !(a == b);
		}

		public override bool Equals(object obj)
		{
			var other = obj as Entity;

			if (ReferenceEquals(other, null))
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			if (GetType() != other.GetType())
			{
				return false;
			}

			if (Id == 0 || other.Id == 0)
			{
				return false;
			}

			return Id == other.Id;
		}
		
		public override int GetHashCode()
		{
			return (GetType().ToString() + Id).GetHashCode();
		}
	}
```

Im using EF Core 1.1.0 targeting .NET 4.6.2 

Proj Structure

Models -> POCO classes
Data -> DbContext class
Web -> Migrations

Because of some .NET Core tooling issues my DbContext is in a Class Library and my Migrations are in the Web project.  Not ideal as I wanted them all in the Data class, but a hack to get things going.  Would this be the problem?

**Comment by mattmckinstry** [comment]
Just to follow up on this.

I added your Nuget package into my projects and added the code lines into an existing migration.  This appears to have been the problem. You need to add this.FixOnModelCreating(modelBuilder); to the DataContext, Create the migration using Package Manager -> Add-Migration and then Add the migrationBuilder.FixMigrationUp<SomeDbContext>(); to the Up method.

Might be worth a small tweak to the documentation.

Great work by the way

**Comment by isukces** [comment]
Thank you for your comment. It is young project and for sure lack of documentation is its weakness. I publish some informations on  [http://efcoreshaman.com/](http://efcoreshaman.com/). It will be wonderful if you want to share your experience on this page.
