### ISSUE TITLE
Support for [DefaultValue] attribute

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#5]
One more thing you could add to future plans:
[DefaultValue] attribute column support
so that everything can be defined using Annotation without having to mix it with FluentAPI.

**Comment by isukces** [comment]
great idea. I will support it soon

**Comment by borisdj** [comment]
I have implemented this and have sent you a pull request.
When you find the time, revise the code, fix if you find something to amend and then merge.
It was fairly simple to add this, so I think it should be OK.
I have tested it and works fine.

**Comment by isukces** [comment]
Check last changes. DefaultValueSqlAttribute (almost same like your) and System.ComponentModel.DefaultValueAttribute are supported now. With default configuration DefaultValueSqlAttributeUpdater is registered after DefaultValueAttributeUpdater so it has higher priority if both attributes are present at the same time.

**Comment by borisdj** [comment]
All right
