### ISSUE TITLE
Columns order bug when explicitly using [ForeignKey] attribute

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#8]
For example:

`public int MovieId { get; set; }`

`[ForeignKey("ObjGenre")]`
`public int GenreId { get; set; }`
`public virtual Genre ObjGenre { get; set; }`

...
`GenreId `comes at first place in db table, when it has `[ForeignKey]` attribute.

**Comment by isukces** [comment]
Will investigate. I have also found other issues with column order when entity class derives from other.

**Comment by borisdj** [comment]
One more thing you could add when you start doing this.
It's sort of new feature but I will just add it here in comment, it is pretty simple.
To add `[SchemaAttribute(string schema)]` for table that will be applicable to Entity classes.

EF has `[TableAttribute(string name, Properties: [Schema = string])` but is order to set custom _Schema_ here you must alse explicity define _tableName_ that becomes redundant when it is default.

_SchemaAttribute_ would only have schema parameter, that allows to set custom _Schema_ while having default _tableName_ meaning the name of the class.

**Comment by isukces** [comment]
please register SchemaAttribute request as separate issue
