### ISSUE TITLE
Adding SchemaAttribute

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#9]
One more thing that could be added is [SchemaAttribute(string schema)] for table that will be applicable to Entity classes.

EF has TableAttribute(string name, Properties: [Schema = string]) but in order to set custom Schema here you must also explicitly define tableName that becomes redundant when it is default.

SchemaAttribute would only have schema parameter, that allows to set custom Schema while having default tableName meaning the name of the class.
Another way to achieve the same, without creating new SchemaAttribute, would be to use TableAttribute and when tableName is null to set it on default class name.
At the moment EF throws exception for this but you could easily re-set tableName in your library before.

**Comment by isukces** [comment]
`DefaultSchemaAttribute` is available.

**Comment by borisdj** [comment]
This DefaultSchemaAttribute is for context but does work when applied on specific Entity class, what the task was about.
